define({
    // Connection tab
    connection: "Connexion",
    // Clients container
    clients: "Client",
    newClients: "Nouveau Client",
    addTrustedClient: "Approuver",
    trustedClients: "Client approuvés",
    removeTrustedClient: "Retirer",
    troubleshooting:
        "Votre casque n'apparait pas dans la liste ? Visitez note page d'aide en anglais <a target= '_blank' href='https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset'>ici</a> ",
    // Manually add client page
    manAddClient: "Ajouter un client manuellement",
    addClient: "Ajouter client",
    deviceName: "Nom du casque",
    deviceNameHelp: "Donnez au casque un nom",
    clientHostname: "Nom d'hôte",
    clientHostnameHelp: "Le même que celui affiché sur votre casque quand le client est lancé",
    ipAddress: "Adresse IP",
    ipHelp: "Entrez l'adresse IP connue du casque",
    addClientButton: "Ajouter client",
    // Configure client page
    configureClient: "Configuration du client",
    configureClientButton: "Configurer",
    configureClientAddIp: "Ajouter une adresse IP",
    configureClientRemoveIp: "Supprimer",
    // Statistics container
    statistics: "Statistiques",
    streamingStatistics: "Statistiques de streaming",
    totalPackets: "Paquets totaux",
    packetRate: "Taux de paquets",
    packetsLostTotal: "Paquets perdus totaux",
    packetsLostPerSecond: "Paquets perdus par sec.",
    totalSent: "Total envoyé",
    sentRate: "Taux d'envoi",
    bitrate: "Débit",
    ping: "Ping",
    totalLatency: "Latence totale",
    encodeLatency: "Latence de l'encodeur",
    encodeLatencyMax: "Latence max. de l'encodeur",
    transportLatency: "Latence de transport",
    decodeLatency: "Latence du décodeur",
    fecPercentage: "Pourcentage de Correction d'Err. Directe (FEC)",
    fecFailureTotal: "Total d'erreur FEC",
    fecFailureInSecond: "Erreurs FEC par sec.",
    clientFPS: "FPS Client",
    serverFPS: "FPS Serveur",
    packets: "Paquets",
    packetss: "Paquets par sec.",
    batteries: "Charge",
    headset: "Casque",
    left: "Gauche",
    right: "Droite",
    // Logging tab
    logging: "Logs",
    // validation errors
    error_DuplicateHostname: "Un autre casque utilise déjà ce nom d'hôte.",
    error_DuplicateIp: "Cette addresse IP est déjà utilisée par ce casque.",
    error_InvalidIp: "N'est pas une addresse IPv4 valide.",
    // Performance graphs tab
    performanceGraphs: "Graphe de performance",
    performanceNetwork: "Réseau",
    performanceReceive: "Réception",
    performanceSend: "Envoi",
    performanceRender: "Rendu",
    performanceIdle: "Inactivité",
    performanceTranscode: "Transcodage",
    performanceEncode: "Encodage",
    performanceDecode: "Décodage",
    performanceTransport: "Transport",
    performanceClientIdle: "Inactivité Client",
    performanceOther: "Autre",
    performanceLatency: "Latence",
    performanceTotalLatency: "Latence Totale",
    performanceFramerate: "Fréquence d'Images",
    performanceServer: "Serveur",
    performanceClient: "Client",
    performanceNoDateCaptured: "Aucune donnée encore capturée",
});
